export default {
    primaryColor: '#1A2A99',
    secColor: '#777E90',
    bgcolor: '#F5F5F5',
    bgWhite: '#FFFF',
    logo: require('../assets/images/Frame.png'),
    email: require('../assets/images/Message.png'),
    lock: require('../assets/images/Lock.png'),
    cake: require('../assets/images/ph_cake.png'),
    eye: require('../assets/images/Show.png'),
    user: require('../assets/images/user.png'),
    gplus: require('../assets/images/gplus.png'),
    gender: require('../assets/images/gender.png'),
    bigcalander: require('../assets/images/bigcalander.png'),
    biggift: require('../assets/images/biggift.png'),
    moneybag: require('../assets/images/moneybag.png'),
    refreshdrop: require('../assets/images/refreshdrop.png'),
    settings: require('../assets/images/settings.png'),
    teeth1: require('../assets/images/teeth1.png'),
    teeth2: require('../assets/images/teeth2.png'),
    teeth3: require('../assets/images/teeth3.png'),
    teeth4: require('../assets/images/teeth4.png'),
    greentick: require('../assets/images/greentick.png'),
    whatsapp: require('../assets/images/whatsapp.png'),
    instagram: require('../assets/images/instagram.png'),
    facebook: require('../assets/images/facebook.png'),
    voicemail: require('../assets/images/voicemail.png'),
};